### ISSUE TITLE
Linux support when

### ISSUE THREAD

**Issue by Gennadiyev** [Chlorie/clu#9]
~~Nobody codes in Windows these days~~ We need Linux utility functions!

**Comment by Chlorie** [comment]
~~VS best IDE but MSVC compiler is s***~~
The biggest blockade to supporting Linux is that there's no standard library implementation of the new formatting facilities introduced in C++20.
I'm currently considering providing an option for the users to use `fmt` instead, which introduces an external dependency, not what I want but I can cope with it.
